/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-20 07:16:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.community;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;
import post.model.vo.*;
import java.util.ArrayList;
import member.model.vo.Member;

public final class notice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/common/cm_aside.jsp", Long.valueOf(1587142506689L));
    _jspx_dependants.put("/views/common/commonheader.jsp", Long.valueOf(1587142507953L));
    _jspx_dependants.put("/views/common/cm_nav.jsp", Long.valueOf(1587142506575L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("post.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
 
    ArrayList<Post> nlist = (ArrayList)request.getAttribute("nlist"); 
    
    PageInfo pi = (PageInfo)request.getAttribute("pi");
    
    int currentPage = pi.getCurrentPage();
    int maxPage = pi.getMaxPage();
    int startPage = pi.getStartPage();
    int endPage = pi.getEndPage();
    
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>커뮤니티 공지사항</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/common/완성본틀.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/community/notice.css\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  \t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-latest.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"script.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"all\">\r\n");
      out.write("\t\t<div id=\"all-wrap\">\r\n");
      out.write("\t\t\t");
      out.write('\r');
      out.write('\n');
 
	Member loginUser = (Member)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header틀</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/common/commonheader.css\">\r\n");
      out.write("     <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"chatdiv\">\r\n");
      out.write("\t\t<div id=\"chatdivleft\">\r\n");
      out.write("\t\t\t<div id=\"chatdivleft1\">\r\n");
      out.write("\t\t\t\t<img id=\"individualtalk\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/갠톡.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"chatdivleft2\">\r\n");
      out.write("\t\t\t\t<img id=\"grouptalk\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/단체톡.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"chatdivright\">\r\n");
      out.write("\t\t\t<div id=\"chattitle\">울타리 톡</div>\r\n");
      out.write("\t\t\t<div id=\"chatsearch\">\r\n");
      out.write("\t\t\t\t<div id=\"chatsearchdiv\">\r\n");
      out.write("\t\t\t\t\t<img id=\"chatsearchimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/검색.png\">\r\n");
      out.write("\t\t\t\t\t<input id=\"chatsearchtext\" type=\"search\" placeholder=\"검색할 회원이나 채팅방을 입력해주세요.\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"body\").click(function(e){\r\n");
      out.write("\t\tif($('#chatdiv').css('display') == 'block'){\r\n");
      out.write("\t\t\tif(!$('#chatdiv').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('#chatdiv').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else if($('#chatdiv').css('display') == 'none'){\r\n");
      out.write("\t\t\tif($('#chatbtn').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('#chatdiv').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t<div id=\"alert-wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"alert\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"alerttitle\">전체알림</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"alertspace\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"body\").click(function(e){\r\n");
      out.write("\t\tif($('.alert').css('display') == 'block'){\r\n");
      out.write("\t\t\tif(!$('.alert').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('.alert').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else if($('.alert').css('display') == 'none'){\r\n");
      out.write("\t\t\tif($('#alertbuttondiv').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('.alert').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t\t<div id=\"header-top\">\r\n");
      out.write("\t\t\t\t\t<div id=\"chatbtn\"><img class=\"headerimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/메신저.png\"></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"alertbuttondiv\"><img class=\"headerimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/알림.png\"></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"header-topR\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"nick\">");
      out.print( loginUser.getNickname() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"nim\">님</div>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"logout\" class=\"top-right\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/logout.me'\">로그아웃</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"header-bottom\">\r\n");
      out.write("\t\t\t\t\t<a href='");
      out.print( request.getContextPath() );
      out.write("/views/main/main.jsp'><img id=\"logoimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/logo.png\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/common/cm_nav.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t\t\t<div id='cssmenu'>\r\n");
      out.write("               <ul>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href='#'>내울타리</a>\r\n");
      out.write("                     <ul id=\"menu1\">\r\n");
      out.write("                        <li><a href='#'>타임라인</a></li>\r\n");
      out.write("                        <li><a href='#'>게시글작성</a></li>\r\n");
      out.write("                        <li><a href='#'>관심회원</a></li>\r\n");
      out.write("                        <li><a href='#'>게시글 즐겨찾기</a></li>\r\n");
      out.write("                        <li><a href='#'>내 위탁환경</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class='active'>\r\n");
      out.write("                     <a href='");
      out.print( request.getContextPath() );
      out.write("/cmAllList.po'>커뮤니티</a>\r\n");
      out.write("                     <ul id=\"menu2\">\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmnlist.po'>공지사항</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmAllList.po'>모아보기</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmdlist.po'>펫일상</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmklist.po'>펫지식</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmrlist.po'>펫리뷰</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmrelist.po'>펫분양</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li><a href='#'>위탁매칭</a>\r\n");
      out.write("                     <ul id=\"menu3\">\r\n");
      out.write("                        <li><a href='#'>위탁검색</a></li>\r\n");
      out.write("                        <li><a href='#'>의뢰 관리</a></li>\r\n");
      out.write("                        <li><a href='#'>내가 남긴 리뷰</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li><a href='#'>마이페이지</a>\r\n");
      out.write("                     <ul id=\"menu4\">\r\n");
      out.write("                        <li><a href='#'>내 정보 관리</a></li>\r\n");
      out.write("                        <li><a href='#'>비밀번호변경</a></li>\r\n");
      out.write("                        <li><a href='#'>회원 탈퇴</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li><a href='#'>고객센터</a>\r\n");
      out.write("                     <ul id=\"menu5\">\r\n");
      out.write("                        <li><a href='#'>공지 사항</a></li>\r\n");
      out.write("                        <li><a href='#'>자주하는 질문</a></li>\r\n");
      out.write("                        <li><a href='#'>1:1 문의</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"asidesection\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/common/cm_aside.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>z\r\n");
      out.write("\t<aside>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmnlist.po'>공지사항</a></li>\r\n");
      out.write("            <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmAllList.po'>모아보기</a></li>\r\n");
      out.write("            <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmdlist.po'>펫일상</a></li>\r\n");
      out.write("            <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmklist.po'>펫지식</a></li>\r\n");
      out.write("            <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmrlist.po'>펫리뷰</a></li>\r\n");
      out.write("            <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmrelist.po'>펫분양</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</aside>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t\t<section>\r\n");
      out.write("        \t\t<div class=\"maincap\">\r\n");
      out.write("        \t\t\t<p class=\"cap_p_head\">공지사항</p><br>\r\n");
      out.write("        \t\t\t<p class=\"cap_p_tag\">커뮤니티 내 공지사항을 모아서 보여드립니다.</p>\r\n");
      out.write("        \t\t\t</div>\r\n");
      out.write("        \t\t\t<hr id=\"mainhr\">\r\n");
      out.write("        \t\t\t<form>\r\n");
      out.write("        \t\t\t<div class=\"search_wrap\">\r\n");
      out.write("        \t\t\t<div class=\"searchselect\">\r\n");
      out.write("\t\t        \t\t<select id=\"date\">\r\n");
      out.write("\t\t        \t\t\t<option value=\"all\" selected>전체기간</option>\r\n");
      out.write("\t\t        \t\t\t<option value=\"1day\">1일</option>\r\n");
      out.write("\t\t        \t\t\t<option value=\"1week\">1주</option>\r\n");
      out.write("\t\t        \t\t\t<option value=\"1month\">1달</option>\r\n");
      out.write("\t\t        \t\t</select>\r\n");
      out.write("\t\t        \t\t<select id=\"searchcon\">\r\n");
      out.write("\t\t        \t\t\t<option value=\"title+content\" selected>제목+내용</option>\r\n");
      out.write("\t\t        \t\t\t<option value=\"onlytitle\">제목만</option>\r\n");
      out.write("\t\t        \t\t\t<option value=\"writer\">작성자</option>\r\n");
      out.write("\t\t        \t\t</select>\r\n");
      out.write("        \t\t\t\t<input type=\"text\" size=20 placeholder=\"검색할 내용을 입력하세요\" class=\"textbox\">\r\n");
      out.write("        \t\t\t\t&nbsp;\r\n");
      out.write("        \t\t\t\t<input type=\"submit\" value=\"검색\" class=\"find\">\r\n");
      out.write("        \t\t\t</div>\r\n");
      out.write("        \t\t\t</div>\r\n");
      out.write("        \t\t\t</form>\r\n");
      out.write("        \t\t<div class=\"array_wrap\">\r\n");
      out.write("        \t\t\t<hr id=\"hr2\">\r\n");
      out.write("        \t\t\t<select>\r\n");
      out.write("        \t\t\t\t<option>최신순</option>\r\n");
      out.write("        \t\t\t\t<option>추천순</option>\r\n");
      out.write("        \t\t\t</select>\r\n");
      out.write("        \t\t\t");
 if(loginUser != null && loginUser.getMemberId().equals("admin")){ 
      out.write("\t\r\n");
      out.write("\t     \t\t<div class=\"writebtn\" onclick=\"location.href='views/community/cmpostWrite.jsp'\"><a>글쓰기</a></div>\r\n");
      out.write("\t     \t\t");
 } 
      out.write("\r\n");
      out.write("        \t\t</div>\r\n");
      out.write("     \t<div class=\"cmcontent\">\r\n");
      out.write("     \t\t<div class=\"cm_wrap\">\r\n");
      out.write("     \t\t\t<div class=\"board_all\">\r\n");
      out.write("     \t\t\t\t<div class=\"boardhead\">\r\n");
      out.write("     \t\t\t\t\t<div class=\"num\">No</div>\r\n");
      out.write("     \t\t\t\t\t<div class=\"tit\">제목</div>\r\n");
      out.write("     \t\t\t\t\t<div class=\"writer\">작성자</div>\r\n");
      out.write("     \t\t\t\t\t<div class=\"wdate\">작성일</div>\r\n");
      out.write("     \t\t\t\t\t<div class=\"recommend\">추천</div>\r\n");
      out.write("     \t\t\t\t\t<div class=\"view\">조회</div>\r\n");
      out.write("     \t\t\t\t</div>\r\n");
      out.write("     \t\t\t\t<div class=\"boardbody\">\r\n");
      out.write("     \t\t\t\t");
 if(nlist.isEmpty()) { 
      out.write("\r\n");
      out.write("     \t\t\t\t\t<div>존재하는 공지사항 없음</div>\r\n");
      out.write("     \t\t\t\t");
 } else { 
     					for(Post n : nlist){
     				
      out.write("\t\r\n");
      out.write("     \t\t\t\t\t<div class=\"boardcontent\">\r\n");
      out.write("     \t\t\t\t\t<div class=\"num\">");
      out.print( n.getPostNum() );
      out.write("</div>\r\n");
      out.write("\t     \t\t\t\t<div class=\"tit\"><a href=\"#\">");
      out.print( n.getPostTitle() );
      out.write("</a></div>\r\n");
      out.write("\t     \t\t\t\t<div class=\"writer\">");
      out.print( n.getMemberid() );
      out.write("</div>\r\n");
      out.write("\t     \t\t\t\t<div class=\"wdate\">");
      out.print( n.getPostDate() );
      out.write("</div>\r\n");
      out.write("\t     \t\t\t\t<div class=\"recommend\">");
      out.print( n.getPostLike() );
      out.write("</div>\r\n");
      out.write("\t     \t\t\t\t<div class=\"view\">");
      out.print( n.getPostclick() );
      out.write("</div>\r\n");
      out.write("     \t\t\t\t\t</div>\t\r\n");
      out.write("     \t\t\t\t");

     					} 
     				}
     				
      out.write(" \r\n");
      out.write("     \t\t\t\t</div>\r\n");
      out.write("\t     \t\t\t</div>\r\n");
      out.write("\t     \t\t</div>\r\n");
      out.write("\t     \t\t<!-- 페이징 -->\r\n");
      out.write("\t     \t\t<div class=\"pagingArea\" align=\"center\">\r\n");
      out.write("\t     \t\t");
 if(!nlist.isEmpty()) { 
      out.write("\r\n");
      out.write("\t     \t\t\t<!-- 맨 처음으로 가는 버튼 -->\r\n");
      out.write("\t     \t\t\t\t<button onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/cmnotice.po?currentPage=1'\">&lt;&lt;</button>\r\n");
      out.write("\t     \t\t\t<!-- 이전 페이지로  -->\r\n");
      out.write("\t\t\t\t<button onclick=\"location.href='");
      out.print( request.getContextPath());
      out.write("/cmnotice.po?currentPage=");
      out.print( currentPage -1 );
      out.write("'\" id=\"beforeBtn\">&lt;</button>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tif(");
      out.print( currentPage );
      out.write(" <= 1){\r\n");
      out.write("\t\t\t\t\t$('#beforeBtn').attr('disabled','true');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<!-- 10개 페이지 목록 -->\r\n");
      out.write("\t\t\t");
 for(int p = startPage; p<= endPage;p++){ 
      out.write("\r\n");
      out.write("\t\t\t\t");
 if(p ==currentPage){ 
      out.write("\r\n");
      out.write("\t\t\t<button id=\"choosen\" disabled>");
      out.print( p );
      out.write("</button>\r\n");
      out.write("\t\t\t\t");
 } else {
      out.write("\r\n");
      out.write("\t\t\t\t\t<button id=\"numBtn\" onclick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/cmnotice.po?currentPage=");
      out.print( p );
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</button>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t<!-- 다음 페이지로 -->\t\r\n");
      out.write("\t\t\t<button id=\"afterBtn\" onclick=\"location.href='");
      out.print( request.getContextPath());
      out.write("/cmnotice.po?currentPage=");
      out.print( currentPage+1 );
      out.write("'\"\t>&gt;</button>\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\tif(");
      out.print( currentPage );
      out.write(" >= ");
      out.print( maxPage );
      out.write("){\r\n");
      out.write("\t\t\t\t\t$('#afterBtn').attr('disabled','true');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<!-- 맨 끝으로 -->\r\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/cmnotice.po?currentPage=");
      out.print(maxPage );
      out.write("'\">&gt;&gt;</button>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t     \t\t</div>\r\n");
      out.write("\t     \t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t$('.boardcontent div').mouseenter(function(){\r\n");
      out.write("\t\t\t\t\t$(this).parent().css({'background':'#EAEAEA','cursor':'pointer'});\r\n");
      out.write("\t\t\t\t}).mouseout(function(){\r\n");
      out.write("\t\t\t\t\t$(this).parent().css('background','none');\r\n");
      out.write("\t\t\t\t}).click(function(){\r\n");
      out.write("\t\t\t\t\tvar num =$(this).parent().children().eq(0).text();\r\n");
      out.write("\t\t\t\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/cmdetail.po?pno=\" + num;\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<footer>from.hoseong</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
