/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-17 12:43:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.trustMatch;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import member.model.vo.*;
import trust.model.vo.*;
import member.model.vo.Member;

public final class matching02_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/common/tr_nav.jsp", Long.valueOf(1587041088178L));
    _jspx_dependants.put("/views/common/tr_aside.jsp", Long.valueOf(1587041088176L));
    _jspx_dependants.put("/views/common/commonheader.jsp", Long.valueOf(1587041193683L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("trust.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	ArrayList<Member> list = (ArrayList<Member>)request.getAttribute("list");
	/* Media proImg = (Media)session.getAttribute("proImg"); */
	/* proImg.getWebName() */

	PageInfo pi =(PageInfo)request.getAttribute("pi");
	
	int currentPage = pi.getCurrentPage();
 	int maxPage = pi.getMaxPage();
 	int startPage = pi.getStartPage();
 	int endPage =pi.getEndPage();
 	
 	String h_area1= request.getParameter("h_area1");
 	String h_area2= request.getParameter("h_area2");
 	String h_area3= request.getParameter("h_area3");
 	String check01= request.getParameter("check01");
 	String[] check = request.getParameterValues("check1");
 	String check2 = request.getParameter("check2");
 	
 	String check1 = "";
 	for(int i=0;i<check.length;i++){ 
		check1  += "&check1="+ check[i]; 
 	}
 	
 	String query = "&h_area1="+h_area1+"&h_area2="+h_area2+"&h_area3="+h_area3+"&check01="+check01+check1+"&check2="+check2;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>커뮤니티용</title>\r\n");
      out.write("</head>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/common/완성본틀.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/trust/matching02.css\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  \t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-latest.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"script.js\"></script>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"all\">\r\n");
      out.write("\t\t<div id=\"all-wrap\">\r\n");
      out.write("\t\t\t");
      out.write('\r');
      out.write('\n');
 
	Member loginUser = (Member)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header틀</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/common/commonheader.css\">\r\n");
      out.write("     <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"chatdiv\">\r\n");
      out.write("\t\t<div id=\"chatdivleft\">\r\n");
      out.write("\t\t\t<div id=\"chatdivleft1\">\r\n");
      out.write("\t\t\t\t<img id=\"individualtalk\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/갠톡.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"chatdivleft2\">\r\n");
      out.write("\t\t\t\t<img id=\"grouptalk\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/단체톡.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"chatdivright\">\r\n");
      out.write("\t\t\t<div id=\"chattitle\">울타리 톡</div>\r\n");
      out.write("\t\t\t<div id=\"chatsearch\">\r\n");
      out.write("\t\t\t\t<div id=\"chatsearchdiv\">\r\n");
      out.write("\t\t\t\t\t<img id=\"chatsearchimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/검색.png\">\r\n");
      out.write("\t\t\t\t\t<input id=\"chatsearchtext\" type=\"search\" placeholder=\"검색할 회원이나 채팅방을 입력해주세요.\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"body\").click(function(e){\r\n");
      out.write("\t\tif($('#chatdiv').css('display') == 'block'){\r\n");
      out.write("\t\t\tif(!$('#chatdiv').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('#chatdiv').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else if($('#chatdiv').css('display') == 'none'){\r\n");
      out.write("\t\t\tif($('#chatbtn').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('#chatdiv').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t<div id=\"alert-wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"alert\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"alerttitle\">전체알림</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"alertspace\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"body\").click(function(e){\r\n");
      out.write("\t\tif($('.alert').css('display') == 'block'){\r\n");
      out.write("\t\t\tif(!$('.alert').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('.alert').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else if($('.alert').css('display') == 'none'){\r\n");
      out.write("\t\t\tif($('#alertbuttondiv').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('.alert').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t\t<div id=\"header-top\">\r\n");
      out.write("\t\t\t\t\t<div id=\"chatbtn\"><img class=\"headerimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/메신저.png\"></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"alertbuttondiv\"><img class=\"headerimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/알림.png\"></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"header-topR\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"nick\">");
      out.print( loginUser.getNickname() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"nim\">님</div>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"logout\" class=\"top-right\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/logout.me'\">로그아웃</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"header-bottom\">\r\n");
      out.write("\t\t\t\t\t<a href='");
      out.print( request.getContextPath() );
      out.write("/views/main/main.jsp'><img id=\"logoimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/logo.png\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/common/cm_nav.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t\t\t<div id='cssmenu'>\r\n");
      out.write("               <ul>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href='#'>내울타리</a>\r\n");
      out.write("                     <ul id=\"menu1\">\r\n");
      out.write("                        <li><a href='#'>타임라인</a></li>\r\n");
      out.write("                        <li><a href='#'>게시글작성</a></li>\r\n");
      out.write("                        <li><a href='#'>관심회원</a></li>\r\n");
      out.write("                        <li><a href='#'>게시글 즐겨찾기</a></li>\r\n");
      out.write("                        <li><a href='#'>내 위탁환경</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href='");
      out.print( request.getContextPath() );
      out.write("/cmAllList.po'>커뮤니티</a>\r\n");
      out.write("                     <ul id=\"menu2\">\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmnlist.po'>공지사항</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmAllList.po'>모아보기</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmdlist.po'>펫일상</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmklist.po'>펫지식</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmrlist.po'>펫리뷰</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmrelist.po'>펫분양</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class='active'><a href='#'>위탁매칭</a>\r\n");
      out.write("                     <ul id=\"menu3\">\r\n");
      out.write("                        <li><a href='#'>위탁검색</a></li>\r\n");
      out.write("                        <li><a href='#'>의뢰 관리</a></li>\r\n");
      out.write("                        <li><a href='#'>내가 남긴 리뷰</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li><a href='#'>마이페이지</a>\r\n");
      out.write("                     <ul id=\"menu4\">\r\n");
      out.write("                        <li><a href='#'>내 정보 관리</a></li>\r\n");
      out.write("                        <li><a href='#'>비밀번호변경</a></li>\r\n");
      out.write("                        <li><a href='#'>회원 탈퇴</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li><a href='#'>고객센터</a>\r\n");
      out.write("                     <ul id=\"menu5\">\r\n");
      out.write("                        <li><a href='#'>공지 사항</a></li>\r\n");
      out.write("                        <li><a href='#'>자주하는 질문</a></li>\r\n");
      out.write("                        <li><a href='#'>1:1 문의</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"asidesection\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/common/tr_aside.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>z\r\n");
      out.write("\t<aside>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"/Ultary/views/trustMatch/matching02.jsp\">위탁검색</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/Ultary/views/trustMatch/matching05.jsp\">의뢰 관리</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/Ultary/views/trustMatch/matching07.jsp\">내가 남긴 리뷰</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</aside>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("            <div id=\"matching\">\r\n");
      out.write("\t\t\t<h1 id=\"title\">위탁검색</h1>\r\n");
      out.write("\t\t\t<p id=\"title-1\">울타리 이용자들의 위탁 품앗이 공간</p>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<br clear=\"all\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"page\">\r\n");
      out.write("\t\t\t\t<div id=\"page1\">\r\n");
      out.write("\t\t\t\t<div id=\"top-bar\">검색필터 펼치기</div>\r\n");
      out.write("\t\t\t\t<div id=\"introview\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t<div id=\"content-box\">\r\n");
      out.write("\t\t    \t<div id=\"matcontent\">\r\n");
      out.write("\t\t    \t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><div id=\"m-in\" class=\"bar\">지역필터</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=place1 class=\"selectall\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"place1\" class=\"pl1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"kw\">강원도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"kk\">경기도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"seoul\">서울시</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"etc\" selected>시/도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"nation1\" class=\"pl1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"kw\">강원도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"kk\">경기도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"seoul\">서울시</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"etc\" selected>군/구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"동/읍을 입력해주세요.\" class=\"pl1\" id=\"text1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"radio1\"><label>위탁</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"radio1\"><label>방문</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"radio1\"><label>산책</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><div id=\"m-in\" class=\"bar\">검색필터1</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"serchfilter1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"check1\" class=\"check\" value=\"픽업여부\"><label>픽업여부</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"check1\" class=\"check\" value=\"마당여부\"><label>마당여부</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"check1\" class=\"check\" value=\"야외산책\"><label>야외산책</label><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"check1\" class=\"check\" value=\"노령동물\"><label>노령동물</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"check1\" class=\"check\" value=\"대형동물\"><label>대형동물</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"check1\" class=\"check\" value=\"목욕가능\"><label>목욕가능</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><div id=\"m-in\" class=\"bar\">검색필터2</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"serchfilter2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"check2\" class=\"check\" value=\"강아지\"><label>강아지</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"check2\" class=\"check\" value=\"고양이\"><label>고양이</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"check2\" class=\"check\" value=\"설치류\"><label>설치류</label><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"check2\" class=\"check\" value=\"어류\"><label>어류&nbsp;</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"check2\" class=\"check\" value=\"파충류\"><label>파충류</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"check2\" class=\"check\" value=\"조류\"><label>조류&nbsp; </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"check2\" class=\"check\" value=\"기타\"><label>기타&nbsp; </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"search01\" onclick='location.href=\"serch1.s1\"'>검색</button>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t </div>\r\n");
      out.write("\t   \t\t\t </form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\t$('#top-bar').click(function(){\r\n");
      out.write("\t\t\t\t\t\t$(this).next().slideToggle();\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<h3 style=\"text-align:center;\">조회결과</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
if(list.isEmpty()){ 
      out.write("\r\n");
      out.write("\t\t\t\t<h2>조회된 리스트가 없습니다.</h2>\r\n");
      out.write("\t\t\t");
 } else{
      out.write("\r\n");
      out.write("\t\t\t\t");
 for(Member m :list){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"content1\" class=\"content-profile\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/Ultary/views/trustMatch/photo.jpg\" id=\"profile\" class=\"profile-photo\">\r\n");
      out.write("\t\t\t\t\t<div class=\"infoDiv\">\r\n");
      out.write("\t\t\t\t\t<span class=\"name\" id=\"name1\">");
      out.print(m.getNickname() );
      out.write("</span><br><br>\r\n");
      out.write("\t\t\t\t\t<span class=\"address\" id=\"class1\">");
      out.print(m.getAddress());
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"infobutton1\">관심등록</div><button id=\"like\">좋아욤</button>\r\n");
      out.write("\t\t\t\t\t<div class=\"infobutton2\" ><a href=\"");
      out.print(request.getContextPath() );
      out.write("/MemberDetail.tu?memberid=");
      out.print(m.getMemberId());
      out.write("\">상세보기</a></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t<div class=\"pagingArea\" align=\"center\">\r\n");
      out.write("\t\t<!-- 페이징 -->\r\n");
      out.write("\t\t");
 if(!list.isEmpty()){ 
      out.write("\r\n");
      out.write("\t\t\t<!-- 맨 처음으로 가는 버튼 만들기-->\r\n");
      out.write("\t\t\t<button type =\"button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/SerchMember.sc?currentPage=1");
      out.print(query);
      out.write("'\">&lt;&lt;</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 이전 페이지로 -->\r\n");
      out.write("\t\t\t<button type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/SerchMember.sc?currentPage=");
      out.print(currentPage-1 );
      out.print(query );
      out.write("'\" id=\"beforeBtn\">&lt;</button>\t\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\tif(");
      out.print(currentPage);
      out.write(" <=1){\r\n");
      out.write("\t\t\t\t\t$('#beforeBtn').attr('disabled','true');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 10개 페이지 목록 -->\r\n");
      out.write("\t\t\t");
 for(int p = startPage; p<=endPage;p++){ 
      out.write("\r\n");
      out.write("\t\t\t\t");
if(p == currentPage){ 
      out.write("\r\n");
      out.write("\t\t\t<button id=\"choosen\" disabled>");
      out.print(p );
      out.write("</button>\r\n");
      out.write("\t\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" id=\"numBtn\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/SerchMember.sc?currentPage=");
      out.print(p);
      out.print(query);
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</button>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 다음 페이지로 -->\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"afterBtn\" onclick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/SerchMember.sc?currentPage=");
      out.print(currentPage+1 );
      out.print(query);
      out.write("'\">&gt;</button>\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\tif(");
      out.print(currentPage);
      out.write(" >= ");
      out.print(maxPage);
      out.write("){\r\n");
      out.write("\t\t\t\t\t$('#afterBtn').attr('disabled','true');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 맨 끝으로 -->\r\n");
      out.write("\t\t\t<button type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/SerchMember.sc?currentPage=");
      out.print(maxPage );
      out.print(query);
      out.write("'\">&gt;&gt;</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<footer>from.hoseong</footer>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
